version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
